export const ADD_NEW_CONTACT = "ADD_NEW_CONTACT";
export const CHANGE_CURRENT_CONTACT = "CHANGE_CURRENT_CONTACT";
export const INIT_CURRENT_CONTACT = "INIT_CURRENT_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_INIT = "FETCH_INIT";
export const FETCH_ERROR = "FETCH_ERROR";
